<?php
$string = '<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://www.rainbowlight.com/our-product</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/digestives</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/feminine-care</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/immune-health</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/bone-health</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/iron</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/protein</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/liver-detox</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/omega-brain-heart-health</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/stress-management</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/womens-health</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/mens-health</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/prenatal-health</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/children-teen-health</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/health-solutions</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/oral-care-breath-freshners</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/vibrance</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/gummy-vitamins</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/probiotics</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/endless-summer-sale</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/mens-essentials</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/vitamins-under-20</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/healthy-aging</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/bestsellers</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/our-product/first-thousand-days</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.5</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/calcium-citrate-berry-wellness</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/calcium-citrate-mini-tabs</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/complete-b-complex</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/power-sours-multivitamin-mineral</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/prenatal-daily-duo-prenatal-one-dha</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/35-plus-mom-baby-pre-postnatal-food-based-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/bear-essentials-multivitamin-mineral</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/berry-d-licious-2500-iu-vitamin-d3-gummy</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/brain-focus-multivitamin-for-teens-adults</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/certified-mens-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/certified-prenatal-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/certified-womens-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/complete-iron-mini-tabs</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/fiber-garden-gummies</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/mens-energy-multivitamin-gummy</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/nail-hair-skin-connection</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/nutristart-multivitamin-powder</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/omegalicious-omega-3-gummies</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/prenatal-dha-smart-essentials</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/probio-active</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/probiolicious-probiotic-gummies</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/sunny-gummies-vitamin-d3-400-iu</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/teen-energy-multivitamin-gummy</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/womens-energy-multivitamin-gummy</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/super-c-1000mg</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/black-cohosh-meno-relief</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/50-plus-mini-tablet</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/active-adult-50-plus-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/active-health-teen-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/advanced-enzyme-system</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/counter-attack</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/kids-one-chewable-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/mens-one-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/womens-one-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/food-based-calcium</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/gummy-vitamin-c-slices</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/menopause-one-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/just-once-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/sunny-gummies-vitamin-d3-1000-iu</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/mental-calm</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/mintasuretm-fresh-breath-capsules-1</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/prenatal-petite-mini-tab-multivitamin-conf</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/prenatal-one-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/nutristars-chewable-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/performance-energy-for-men-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/teen-girls-multivitamin-plus-healthy-skin-support</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/prenatal-multivitamin-plus-immune-support</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/young-men-s-multivitamin-plus-healthy-skin-support</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/womens-multivitamin-plus-balance-energy</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/men-s-multivitamin-plus-stress-support</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/womens-multivitamin-plus-stress-support</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/mens-multivitamin-plus-energy-vitality</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vegan-lean-protein</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-pre-conception-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-postnatal-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-nutristart-plus-multivitamin-powder</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-trimester-1-prenatal-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-trimester-2-prenatal-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-trimester-3-prenatal-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/prenatal-one-non-gmo-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/mens-one-non-gmo-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/womens-one-non-gmo-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/prenatal-precious-gems-non-gmo-gummies</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/active-adult-50-non-gmo-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/probiolicious-plus-non-gmo-gummies</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/magnesium-calcium-plus</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>1.0</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/enable-cookies</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/service-unavailable</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/about/through-transparency-purity-quality</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/about/how-we-care</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/careers</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/faqs</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/home6</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/shopping-online-satisfaction</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/the-company</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/practitioners</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/terms-conditions</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/privacy-security</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-teen-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-womens-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/vibrance-prenatal-multivitamin</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/limited-time-offer</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/email-offer</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/not-found-404</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/prenatal-vitamins</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/first-thousand-days</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/promotional-disclaimers</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/information-for-retailers</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/retailer-purchase-terms-and-conditions</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/minimum-advertised-pricing-policy</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
   <url>
      <loc>https://www.rainbowlight.com/product-survey-thanks</loc>
      <lastmod>2019-03-30</lastmod>
      <changefreq>daily</changefreq>
      <priority>0.2</priority>
   </url>
</urlset>';

preg_match_all('#\bhttps?://[^,\s()<>]+(?:\([\w\d]+\)|([^,[:punct:]\s]|/))#', $string, $match);


$arr = $match[0];
$string = implode('<br>', $arr);
echo '<pre>';
print_r($string);

?>